### ISSUE TITLE
Please add https://www.bloombergquint.com/ 

### ISSUE THREAD

**Issue by XmansGhost** [iamadamdev/bypass-paywalls-firefox#100]
This used to work for free but now it has turned paid since few days. Please add this.

**Comment by iamadamdev** [comment]
New site requests:
Visit an article on the site you want to bypass the paywall for and copy the article title.
Open up a new Private window (Ctrl+Shift+P) and paste the article title into Google.
Click on the same article from the Google search results page. If it loads without a paywall you can submit a request to add the site, otherwise my extension cannot bypass it either.

**Comment by mmahesh979** [comment]
I just checked, it can. The contents of the page are loaded too, i checked the html/css. The paywall blocks it as an overlay. I will try to submit a pull request but unfortunately my JS skills are extremely poor and it could take a while. 

In the meanwhile, those who still want to read the news can use the reader view (f9) to bypass the paywall.

Cheers,
M

**Comment by XmansGhost** [comment]
Thanks guys its working now. Closing this for some time :D
