### ISSUE TITLE
Please add Geopolitical Futures

### ISSUE THREAD

**Issue by inteloperator** [iamadamdev/bypass-paywalls-firefox#107]
https://geopoliticalfutures.com/

**Comment by iamadamdev** [comment]
New site requests:
Visit an article on the site you want to bypass the paywall for and copy the article title.
Open up a new Private window (Ctrl+Shift+P) and paste the article title into Google.
Click on the same article from the Google search results page. If it loads without a paywall you can submit a request to add the site, otherwise my extension cannot bypass it either.
