### ISSUE TITLE
Simply doesn't work for Washington Post

### ISSUE THREAD

**Issue by gitdjc** [iamadamdev/bypass-paywalls-firefox#12]
The subject says it. Firefox, Linux Mint, uBlock Origin, but not working to bypass the paywall. Suggestions?

**Comment by Vash63** [comment]
Same issue here. I have a paid account and had to disable it for WaPo as it would continually redirect me to the GDPR page (I'm located in the Netherlands), or give an error that there was a network error if I tried to log into my account. Disabling this addon for WaPo fixed the issue.

**Comment by iamadamdev** [comment]
Still works for me. I unchecked the site in options, clicked a bunch of articles until I got the paywall, then rechecked the site in options, hit save, went to a new article and it loaded fine.

**Comment by Vash63** [comment]
Still doesn't work for me. If I don't try to log in it just endlessly cycles through the GDPR page. If I do try to log in I get the below error. Disabling this addon fixes the issue.

I've tested this on both Linux and MacOS on two different machines on two different networks (Both in Europe, hence the GDPR page). 

![screenshot from 2018-06-26 02-00-12](https://user-images.githubusercontent.com/3086017/41881644-bf72f892-78e4-11e8-8694-a3114b019112.png)

If there's any detail or debugging info that I could supply I would be happy to, but it is kind of rude to just close an issue because you can't duplicate when multiple people are reporting it.

**Comment by iamadamdev** [comment]
That explains it. Since I'm not in the EU I'm not getting that GDPR page so it will be a little harder for me to debug.
Can you download the open source repo and edit `background.js` and add `'washingtonpost.com'` to both the `allow_cookies` and `remove_cookies` arrays? Then goto `about:debugging` to load the extension and test it out (be sure to remove the production Bypass Paywalls add-on first)

**Comment by Vash63** [comment]
That seems to be working for me. I was able to click the 'browse free' button and check the accept box for their cookies now without it giving any network errors or refreshing to the same page. Tested 6 articles after from the home page with no issues.

**Comment by iamadamdev** [comment]
It works now for you? Or only after you added it to those arrays?

**Comment by Vash63** [comment]
After editing the arrays it works. The build on AMO does not as of yesterday.

**Comment by iamadamdev** [comment]
Try v1.2.9 on AMO

**Comment by Vash63** [comment]
New version works now, thanks.
