### ISSUE TITLE
unlock inpact-hardware

### ISSUE THREAD

**Issue by insituchapuis** [iamadamdev/bypass-paywalls-firefox#126]
hello

if it's possible to add this french site : https://www.inpact-hardware.com/article/1102/unifi-controller-dubiquiti-utilisez-raspberry-pi-comme-cloud-key

thx in advance

Laurent

**Comment by iamadamdev** [comment]
New site requests:
Visit an article on the site you want to bypass the paywall for and copy the article title.
Open up a new Private window (Ctrl+Shift+P) and paste the article title into Google.
Click on the same article from the Google search results page. If it loads without a paywall you can submit a request to add the site, otherwise my extension cannot bypass it either.
