### ISSUE TITLE
https://molndalsposten.se/nyheter/celebert-besok-nar-brittiska-varumarken-poppar-upp-i-gallerian/

### ISSUE THREAD

**Issue by ilmirka85** [iamadamdev/bypass-paywalls-firefox#131]

**Comment by iamadamdev** [comment]
New site requests:
Visit an article on the site you want to bypass the paywall for and copy the article title.
Open up a new Private window (Ctrl+Shift+P) and paste the article title into Google.
Click on the same article from the Google search results page. If it loads without a paywall you can submit a request to add the site, otherwise my extension cannot bypass it either.
