### ISSUE TITLE
Scientificamerican.com fastcompany.com

### ISSUE THREAD

**Issue by vipuldsharma** [iamadamdev/bypass-paywalls-firefox#133]
Sir please include Scientificamerican.com and fastcompany.com in your awesome plugin please. I will be highly indebted to you sir

**Comment by iamadamdev** [comment]
Are you using uBlock Origin? I am not seeing paywalls on either of those sites.

**Comment by vipuldsharma** [comment]
Yeah actually, the pay wall is at scientic American website magazine section only. Not on fast company though. So please sir can you please fix the magazine pay wall of scientific American?

**Comment by vipuldsharma** [comment]
To be precise sir, I am not able to access there magazine articles sir

https://www.scientificamerican.com/store/archive/?magazineFilterID=Scientific%20American%20Magazine
It is when I open any magazine from this link, I am not able to read articles,that is, there is a pay wall in the magazine section. Please help sir

**Comment by vipuldsharma** [comment]
Sir is there anything that can be done with regards to my query in above comment, please?

**Comment by iamadamdev** [comment]
That is a hard paywall. You need to pay for those...they are not provided online for free.

New site requests:
Visit an article on the site you want to bypass the paywall for and copy the article title.
Open up a new Private window (Ctrl+Shift+P) and paste the article title into Google.
Click on the same article from the Google search results page. If it loads without a paywall you can submit a request to add the site, otherwise my extension cannot bypass it either.

**Comment by vipuldsharma** [comment]
Ok sir got your point
