### ISSUE TITLE
economictimes webaite

### ISSUE THREAD

**Issue by harshisthere** [iamadamdev/bypass-paywalls-firefox#134]
Popular news source in India.
Example url
https://prime.economictimes.indiatimes.com/news/68001697/consumer/bahut-hard-inside-becks-ice-vs-kingfisher-storm-the-spicy-new-rivalry-in-indias-strong-beer-market?utm_source=WAP&utm_medium=current&utm_campaign=etprimedistribution

**Comment by iamadamdev** [comment]
New site requests:
Visit an article on the site you want to bypass the paywall for and copy the article title.
Open up a new Private window (Ctrl+Shift+P) and paste the article title into Google.
Click on the same article from the Google search results page. If it loads without a paywall you can submit a request to add the site, otherwise my extension cannot bypass it either.
