### ISSUE TITLE
Please add support for these sites...

### ISSUE THREAD

**Issue by TesterMan247** [iamadamdev/bypass-paywalls-firefox#142]
Please fix your extension to work with the following sites:

adelaidenow.com.au
couriermail.com.au
dailytelegraph.com.au
geelongadvertiser.com.au
goldcoastbulletin.com.au
heraldsun.com.au
independent.co.uk
theaustralian.com.au
thetimes.co.uk

Thanks a lot.

**Comment by iamadamdev** [comment]
Those are all news.com.au sites and they change their bypassing rules often.

New site requests:
Visit an article on the site you want to bypass the paywall for and copy the article title.
Open up a new Private window (Ctrl+Shift+P) and paste the article title into Google.
Click on the same article from the Google search results page. If it loads without a paywall you can submit a request to add the site, otherwise my extension cannot bypass it either.

**Comment by TesterMan247** [comment]
Well, all those sites work with the extensions Anti-Paywall.

Therefore, those sites can certainly be bypassed.

I just thought if they could get it to work, so could you.

Plus, their extension hasn't been updated in ages, and yet it STILL works with all those sites I mentioned before.

**Comment by iamadamdev** [comment]
So why don't you just use that extension? 🤦‍♂️

**Comment by TesterMan247** [comment]
I am.

I just thought you might like to make yours better so that it could rule them all, especially since it can be done.

**Comment by iamadamdev** [comment]
Added a few of them in the latest version v1.5.2
