### ISSUE TITLE
WaPo doesn't work für me

### ISSUE THREAD

**Issue by NormaJeanBaker** [iamadamdev/bypass-paywalls-firefox#40]
The Washington Post doesn't work for me. It's stuck in an endless loop, always asking me for the "Free browsing" or choosing a subskrition model over and over again after I have confirmed the cookie policy. Switching off Ublock Origin doesn't change anything.

**Comment by dandelion1974** [comment]
I have the same problem.

**Comment by frm1001xplrr** [comment]
Same here.

Seems like WaPo is setting a cookie that needs to be there, and if it's not, it redirects to subscription options. Choosing the "free" option likely sets a cookie, that should allow to view an article. But when that cookie is deleted wapo redirects back to subscription options. Endless loop...

**Comment by iamadamdev** [comment]
It seems to work from the U.S. One solution would be to use a free VPN addon and set your country to the U.S.

**Comment by BubiBalboa** [comment]
I got the same problem. Endless loop for GDPR consent. Whitelisting WaPo would be a solution.

**Comment by lbschenkel** [comment]
I'm experiencing the same issue and I believe that's an issue with this add-on. There's a different one, called Burlesco, which has the same purpose as this one but focused on Brazilian media. It happens to support WaPo as well, and if I enable the bypass on that one, it works.

It looks like the bypass, as implemented by this add-on, is incomplete in the sense that it works for IPs inside the US but not foreign IPs. Burlesco's implementation on the other hand does work. Do you want me to take a look at the implementation and report the difference so you can add the missing pieces in order to allow non-US users to bypass the paywall?

**Comment by iamadamdev** [comment]
Yes please do so, or if you figure out the fix you can even submit the PR yourself.
