### ISSUE TITLE
With Bloomberg.com ticked in the setting, bloomberg.com always redirects to its Asia edition.

### ISSUE THREAD

**Issue by mickeyseo** [iamadamdev/bypass-paywalls-firefox#55]
I appreciate your support.

This is my user environment.
Firefox 62.0 (32bit)
Installed add-ons: Bypass Paywalls, Default Bookmark Folder, uBlock Origin
I always use Private Browsing mode
Tracking Protection is switched off

I can access the Europe edition, the Middle East edition and the Africa edition without any problems. Also, a new tab of the Japan edition presents normally.

However, with Bloomberg.com ticked in the setting, bloomberg.com always redirects to its Asia edition. I turned Tracking Protection on and off, but the glitch still existed. With Bloomberg.com unchecked, I can visit the US edition and the Asia edition.

Here is a video capture to help you understand my inquiry.
https://youtu.be/FyXcx_WGbcQ

I would like to browse Bloomberg.com when it is ticked in the setting to bypass the paywall. Can you please help me fix this problem?

**Comment by iamadamdev** [comment]
That is because you are located in Asia, but it's weird it doesn't allow it to set to U.S. 
Two solutions:
1. try a free VPN addon like https://addons.mozilla.org/en-US/firefox/addon/anonymox/ and set your location to US
2. turn off bloomberg in options like you did, goto u.s. site, then turn it on, and click on the article you want to read
