### ISSUE TITLE
could you add japanese news site

### ISSUE THREAD

**Issue by fatewx** [iamadamdev/bypass-paywalls-firefox#93]
could you add japanese language news sites like nikkei and asahi?

**Comment by iamadamdev** [comment]
urls please?

**Comment by fatewx** [comment]
https://www.asahi.com/
https://www.nikkei.com/
http://jbpress.ismedia.jp/
https://www.sankei.com/
http://premium.yomiuri.co.jp/pc/#!/list_%2523IMPTNT

**Comment by iamadamdev** [comment]
Have you verified they all work by using the google referral trick?:

**New site requests:**
Visit an article on the site you want to bypass the paywall for and copy the article title.
Open up a new Private window (Ctrl+Shift+P) and paste the article title into Google.
Click on the same article from the Google search results page. If it loads without a paywall you can submit a request to add the site, otherwise my extension cannot bypass it either.

**Comment by fatewx** [comment]
got it. It loads with a paywall. Anyway, thank you.

**Comment by fatewx** [comment]
yeah, none of them work. The paywall of Japanese news sites might be different from the English ones.
