### ISSUE TITLE
request: qz.com

### ISSUE THREAD

**Issue by symmetryrtemmys** [iamadamdev/bypass-paywalls-firefox#98]
Thanks for your steadfast work and useful extension!

**Comment by iamadamdev** [comment]
What article are you seeing a paywall on? I was able to load 10+ articles just fine (I have uBlock Origin installed).

**Comment by symmetryrtemmys** [comment]
https://qz.com/1474885/derek-blasberg-is-making-youtube-fashionable/

**Comment by iamadamdev** [comment]
Premium articles won't work. You can test this by:

New site requests:
Visit an article on the site you want to bypass the paywall for and copy the article title.
Open up a new incognito window (Ctrl+Shift+N) and paste the article title into Google.
Click on the same article from the Google search results page. If it loads without a paywall you can submit a request to add the site, otherwise my extension cannot bypass it either.
